image: openjdk:8

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
          - gradle
        script:
          - bash ./gradlew clean build -xtest
        services:
          - mongo
    - step:
        name: Deploy to Heroku
        deployment: staging
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

definitions:
  services:
    mongo:
      image: mongo